var EVENTS = {
    VERIFY_USER      : 'VERIFY_USER',
    USER_CONNECTED   : 'USER_CONNECTED',
    USER_DISCONNECTED: 'USER_DISCONNECTED',
    MESSAGE_SENT     : 'MESSAGE_SENT',
    MESSAGE_RECEIVED : 'MESSAGE_RECEIVED',
    LOGOUT           : 'LOGOUT',
    TYPING           : 'TYPING',
    COMMUNITY_CHAT   : 'COMMUNITY_CHAT',
    PRIVATE_MESSAGE  : 'PRIVATE_MESSAGE'
}

module.exports = EVENTS;